#pragma once

enum e_simulation_queue_player_event_type : uint32
{
	_simulation_queue_player_event_update = 0,
	k_simulation_queue_player_event_count,
	k_simulation_queue_player_event_size_bits = 2
};

enum e_simulation_queue_game_global_event_type : int8
{
	_simulation_queue_game_global_event_type_claim_authority_gameworld,
	_simulation_queue_game_global_event_type_game_simulation_server,
	_simulation_queue_game_global_event_type_game_simulation_client,
	_simulation_queue_game_global_event_type_game_finish,
	_simulation_queue_game_global_event_type_revert_map,
	_simulation_queue_game_global_event_type_reset_map,
	_simulation_queue_game_global_event_type_save_and_quit,
	_simulation_queue_game_global_event_type_simulation_reset_complete,
	_simulation_queue_game_global_event_type_simulation_reset_initiate,
	_simulation_queue_game_global_event_type_simulation_going_active,
	k_simulation_queue_game_global_event_count,

	k_simulation_queue_game_global_event_type_bits = 4,
	k_simulation_queue_game_global_event_type_none = NONE
};

struct s_simulation_queue_player_event_data
{
	bool active;
};

bool simulation_queue_game_global_event_requires_cutoff(const struct s_simulation_queue_element* element);

void simulation_queue_game_global_event_insert(e_simulation_queue_game_global_event_type global_event_type);
void simulation_queue_game_global_event_apply(const struct s_simulation_queue_element* element);

void simulation_queue_player_event_insert(e_simulation_queue_player_event_type event_type, datum player_index, const s_simulation_queue_player_event_data* event_data);
void simulation_queue_player_event_apply(const struct s_simulation_queue_element* element);

void simulation_queue_player_update_insert(const struct simulation_player_update* player_update);
void simulation_queue_player_update_apply(const struct s_simulation_queue_element* element);

void simulation_queue_gamestates_delete_insert(const struct s_simulation_queue_gamestate_clear_data* gamestate_clear_data);
void simulation_queue_gamestates_delete_apply(const struct s_simulation_queue_element* element);
